package com.smj.workhub.activity.entity;

public enum ActivityAction {
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED,
    WORKSPACE_RESTORED,

    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_RESTORED,

    TASK_CREATED,
    TASK_UPDATED,
    TASK_ASSIGNED,
    TASK_STATUS_CHANGED,
    TASK_STATUS_UPDATED,
    TASK_RESTORED,
    TASK_DELETED,

    COMMENT_CREATED,
    COMMENT_UPDATED,
    COMMENT_DELETED,

    ATTACHMENT_UPLOADED,
    ATTACHMENT_DELETED
}