package com.smj.workhub.notification.entity;

public enum NotificationType {

    // WORKSPACE EVENTS
    WORKSPACE_CREATED,
    WORKSPACE_UPDATED,
    WORKSPACE_DELETED,
    WORKSPACE_RESTORED,
    WORKSPACE_MEMBER_ADDED,
    WORKSPACE_MEMBER_REMOVED,
    WORKSPACE_ROLE_UPDATED,

    // PROJECT EVENTS
    PROJECT_CREATED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_RESTORED,

    // TASK EVENTS
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_RESTORED,
    TASK_STATUS_CHANGED,
    TASK_ASSIGNED,          // future-ready

    // COMMENT EVENTS
    COMMENT_ADDED,
    COMMENT_UPDATED,
    COMMENT_DELETED,
    COMMENT_REPLIED,
    COMMENT_CREATED,// for threaded discussions

    // ATTACHMENT EVENTS
    ATTACHMENT_UPLOADED,
    ATTACHMENT_DELETED

}